### Accessing/Changing specific elements, rows, columns, etc

In [16]:
import numpy as np

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape # 2x7

(2, 7)

In [19]:
#accesing element [r,c]
print(a[1,5])

13


In [20]:
# get a specific row
print(a[0,:])
print(a[1,:])


[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [21]:
# get a specific colunm
print(a[:,4])
print(a[:,3])

[ 5 12]
[ 4 11]


In [22]:
#[start_index:end_index:step_size]
print(a[0,1:-1:2])
print(a[1,1:-1:1])

[2 4 6]
[ 9 10 11 12 13]


In [23]:
#changing elements

a[1,5]=15 #specific row
print(a)

a[:,2]=5 #entire colunm
print(a)

a[0,:]=2 #entire row
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 15 14]]
[[ 2  2  2  2  2  2  2]
 [ 8  9  5 11 12 15 14]]


### 3-D array


In [24]:
b= np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(b)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [25]:
#get specific element
print(b[0,1,0])
print(b[:,1,:])

3
[[3 4]
 [5 6]]


In [26]:
#replace
b[:,1,:]=[[9,9],[10,11]]
print(b)

[[[ 1  2]
  [ 9  9]]

 [[ 4  5]
  [10 11]]]
