In [1]:
import numpy as np

### Linear Algebra

In [2]:
a = np.ones((2,3))
print(a)
print()

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [3]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [5]:
 #dot product
dot_product = np.dot(a, b)
# OR
dot_product = a @ b

print(dot_product)


[[6. 6.]
 [6. 6.]]


In [6]:
# transpose
a_T = a.T
print(a_T)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# cross product
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

cross = np.cross(v1, v2)
print(cross)


[-3  6 -3]


In [11]:
M = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(M)

print("Eigenvalues:", eigenvalues,"\n")
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [5. 2.] 

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [12]:
#inverse 
inverse = np.linalg.inv(M)
print(inverse)


[[ 0.3 -0.2]
 [-0.1  0.4]]


In [15]:
#rank of matrix
rank = np.linalg.matrix_rank(M)
print(rank)


2


In [17]:
# norm(magnitude)
norm = np.linalg.norm(v1)
print(norm)


3.7416573867739413


Solving Linear Equation (IMP)

In [13]:
A = np.array([[3,1],
              [1,2]])
B = np.array([9,8])

X = np.linalg.solve(A, B)
print(X)


[2. 3.]
