### Initializing diffrenet types of arrays

In [8]:
import numpy as np

In [9]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


In [10]:
# all 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# All 1's matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [12]:
# any other number
np.full((2,2), 24)

array([[24, 24],
       [24, 24]])

In [14]:
# any other number (full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [15]:
#random decimal number
np.random.rand(4,2)

array([[0.47128783, 0.87062759],
       [0.83522655, 0.6727427 ],
       [0.54466274, 0.038012  ],
       [0.61816123, 0.08594631]])

In [16]:
np.random.random_sample(a.shape)

array([[0.52965155, 0.89206475, 0.60014282, 0.69512654, 0.67897735,
        0.70069295, 0.12664723],
       [0.3436133 , 0.01665589, 0.47921747, 0.83124612, 0.94829658,
        0.99211101, 0.89433456]])

In [18]:
# random int values
np.random.randint(10,size=(3,3))

array([[0, 3, 5],
       [8, 3, 7],
       [7, 3, 5]], dtype=int32)

In [19]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# repeating the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:
op= np.ones((5,5))
print(op)

z=np.zeros((3,3))
z[1,1]=9
print(z)
print()

op[1:4,1:4]=z
print(op)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## be careful when copying array!!!


In [ ]:
a =np.array([1,2,3])
b=a
b[0]=100

print(a)

[100   2   3]


In [30]:
a =np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)

[1 2 3]
