# Numpy

### Loading Numpy

In [33]:
import numpy as np

### Array

In [34]:
#Creating Array

#1d
a=np.array([1,2,3])
print(a)

print()

#2d
b=np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [35]:
#GEt dimentions of an array
b.ndim

2

In [36]:
# get shape
print(b.shape)
print(a.shape)

(2, 3)
(3,)


In [ ]:
# get type
b.dtype

dtype('int64')

In [38]:
#get size
a.itemsize

8

In [39]:
#get total size
a.size

3